apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wg-easy-tls
  namespace: joledev-vpn
spec:
  secretName: wg-easy-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - admin.vpn.joledev.com
